version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes: 
      - .:/workspace/bawk
      - saved-models:/app
    environment: 
      FLASK_ENV: production
    platform: "linux/amd64"
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: "16g"
volumes:
  saved-models:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/ubuntu/saved_models"
