version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - .:/workspace/bawk
    environment: 
      FLASK_ENV: development
    platform: "linux/amd64"
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: "8gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
